name: Browser Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Update Chrome path for Linux
      run: |
        CHROME_PATH=$(which chrome)
        # Update the getChromePath function in the test runner to use the correct path on Linux
        sed -i "s#return '/usr/bin/google-chrome';#return '$CHROME_PATH';#" tests/run-browser-tests-core.js
    
    - name: Run browser tests
      run: npm test
      
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          tests/static/browser-tests.html 